# Generated by Django 4.0.3 on 2022-03-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('lienimage', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantite', models.IntegerField()),
                ('soustitre', models.CharField(max_length=200)),
            ],
        ),
    ]
